name: Run tests

on:
  pull_request:
    branches: [ "unittest" , "dev" , "main" ] # i vårt test fall kommer vi brancha ut från branch: unittest


jobs:
  test:
      runs-on: ubuntu-latest # vilken servermiljö ska användas - använd linux/ubuntu

      steps:
        #1
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'

      - name: Run tests with maven
        run: mvn clean test

